title: Thomas Cokelaer
description: Bioinformatics researcher & open-source software developer
theme: jekyll-theme-cayman
show_downloads: false
url: https://thomas-cokelaer.github.io

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Post: "post"


